<<<<<<< HEAD
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Unga branch name 'master' ah irundha, idha 'master' nu mathikonga
=======
name: Deploy React Vite to GitHub Pages

on:
  push:
    branches: ['main'] # unga branch name 'master' ah irundha, idha 'master' nu mathikonga
>>>>>>> ec746734adc4554fca8f52a78d1505292564987b
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

<<<<<<< HEAD
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
=======
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
>>>>>>> ec746734adc4554fca8f52a78d1505292564987b
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

<<<<<<< HEAD
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite build aagura folder name idhudhan

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
=======
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite build folder idhuthaan

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
>>>>>>> ec746734adc4554fca8f52a78d1505292564987b
